<?php

if( !empty( get_option( 'addon_main_typekit_font_face', '' ) ) ) {

    $custom_styles .= '
        h1, h2, h3, h4, h5, h6,
        .comments-title,
        .comment-author,
        #reply-title,
        #site-footer .widget-title,
        .accordion_title,
        .ui-tabs-anchor,
        .products .button,
        .site-title a,
        .post_meta_archive a,
        .post_meta a,
        .post_tags a,
         #nav-below a,
        .list_categories a,
        .list_shop_categories a,
        .main-navigation > ul > li > a,
        .main-navigation .mega-menu > ul > li > a,
        .more-link,
        .top-page-excerpt,
        .select2-search input,
        .product_after_shop_loop_buttons a,
        .woocommerce .products-grid a.button,
        .page-numbers,
        input.qty,
        .button,
        button,
        .button_text,
        input[type="button"],
        input[type="reset"],
        input[type="submit"],
        button[type="submit"],
        .woocommerce a.button,
        .woocommerce-page a.button,
        .woocommerce button.button,
        .woocommerce-page button.button,
        .woocommerce input.button,
        .woocommerce-page input.button,
        .woocommerce #respond input#submit,
        .woocommerce-page #respond input#submit,
        .woocommerce #content input.button,
        .woocommerce-page #content input.button,
        .woocommerce a.button.alt,
        .woocommerce button.button.alt,
        .woocommerce input.button.alt,
        .woocommerce #respond input#submit.alt,
        .woocommerce #content input.button.alt,
        .woocommerce-page a.button.alt,
        .woocommerce-page button.button.alt,
        .woocommerce-page input.button.alt,
        .woocommerce-page #respond input#submit.alt,
        .woocommerce-page #content input.button.alt,
        .yith-wcwl-wishlistexistsbrowse.show a,
        .share-product-text,
        .tabs > li > a,
        label,
        .comment-respond label,
        .product_meta_title,
        .woocommerce table.shop_table th,
        .woocommerce-page table.shop_table th,
        #map_button,
        .coupon_code_text,
        .woocommerce .cart-collaterals .cart_totals tr.order-total td strong,
        .woocommerce-page .cart-collaterals .cart_totals tr.order-total td strong,
        .cart-wishlist-empty,
        .wishlist-empty,
        .cart-empty,
        .return-to-shop .wc-backward,
        .order-number a,
        .account_view_link,
        .post-edit-link,
        .from_the_blog_title,
        .icon_box_read_more,
        .vc_pie_chart_value,
        .shortcode_banner_simple_bullet,
        .shortcode_banner_simple_height_bullet,
        .category_name,
        .woocommerce span.onsale,
        .woocommerce-page span.onsale,
        .out_of_stock_badge_single,
        .out_of_stock_badge_loop,
        .page-numbers,
        .post-nav-links span,
        .post-nav-links a,
        .add_to_wishlist,
        .yith-wcwl-wishlistaddedbrowse,
        .yith-wcwl-wishlistexistsbrowse,
        .filters-group,
        .product-name,
        .woocommerce-page .my_account_container table.shop_table.order_details_footer tr:last-child td:last-child .amount,
        .customer_details dt,
        .widget h3,
        .widget .total .amount,
        .wishlist-in-stock,
        .wishlist-out-of-stock,
        .comment-reply-link,
        .comment-edit-link,
        .widget_calendar table thead tr th,
        .page-type,
        .mobile-navigation a,
        table thead tr th,
        .portfolio_single_list_cat,
        .portfolio-categories,
        .shipping-calculator-button,
        .vc_btn,
        .vc_btn2,
        .vc_btn3,
        .account-tab-item .account-tab-link,
        .account-tab-list .sep,
        ul.order_details li,
        ul.order_details.bacs_details li,
        .widget_calendar caption,
        .widget_recent_comments li a,
        .edit-account legend,
        .widget_shopping_cart li.empty,
        .cart-collaterals .cart_totals .shop_table .order-total .woocommerce-Price-amount,
        .woocommerce table.cart .cart_item td a,
        .woocommerce #content table.cart .cart_item td a,
        .woocommerce-page table.cart .cart_item td a,
        .woocommerce-page #content table.cart .cart_item td a,
        .woocommerce table.cart .cart_item td span,
        .woocommerce #content table.cart .cart_item td span,
        .woocommerce-page table.cart .cart_item td span,
        .woocommerce-page #content table.cart .cart_item td span,
        .woocommerce-MyAccount-navigation ul li,
        .cd-quick-view .cd-item-info .product_infos .quickview-badges .onsale,
        .woocommerce-info.wc_points_rewards_earn_points,
        .woocommerce-info, .woocommerce-error, .woocommerce-message,
        .woocommerce .cart-collaterals .cart_totals .cart-subtotal th,
        .woocommerce-page .cart-collaterals .cart_totals .cart-subtotal th,
        .woocommerce .cart-collaterals .cart_totals tr.shipping th,
        .woocommerce-page .cart-collaterals .cart_totals tr.shipping th,
        .woocommerce .cart-collaterals .cart_totals tr.order-total th,
        .woocommerce-page .cart-collaterals .cart_totals tr.order-total th,
        .woocommerce .cart-collaterals .cart_totals h2,
        .woocommerce .cart-collaterals .cross-sells h2,
        .woocommerce-cart #content table.cart td.actions .coupon #coupon_code,
        form.checkout_coupon #coupon_code,
        .woocommerce-checkout .woocommerce-info,
        .shopkeeper_checkout_coupon,
        .shopkeeper_checkout_login,
        .minicart-message,
        .woocommerce .woocommerce-checkout-review-order table.shop_table tfoot td,
        .woocommerce .woocommerce-checkout-review-order table.shop_table tfoot th,
        .woocommerce-page .woocommerce-checkout-review-order table.shop_table tfoot td,
        .woocommerce-page .woocommerce-checkout-review-order table.shop_table tfoot th,
        .no-products-info p,
        .getbowtied_blog_ajax_load_button a,
        .getbowtied_ajax_load_button a,
        .index-layout-2 ul.blog-posts .blog-post article .post-categories li a,
        .index-layout-3 .blog-posts_container ul.blog-posts .blog-post article .post-categories li a,
        .index-layout-2 ul.blog-posts .blog-post .post_content_wrapper .post_content .read_more,
        .index-layout-3 .blog-posts_container ul.blog-posts .blog-post article .post_content_wrapper .post_content .read_more,
        .woocommerce .woocommerce-breadcrumb,
        .woocommerce-page .woocommerce-breadcrumb,
        .woocommerce .woocommerce-breadcrumb a,
        .woocommerce-page .woocommerce-breadcrumb a,
        .product_meta,
        .product_meta span,
        .product_meta a,
        .product_layout_classic div.product span.price,
        .product_layout_classic div.product p.price,
        .product_layout_2 div.product span.price,
        .product_layout_2 div.product p.price,
        .product_layout_3 div.product span.price,
        .product_layout_3 div.product p.price,
        .product_layout_4 div.product span.price,
        .product_layout_4 div.product p.price,
        .related-products-title,
        .product_socials_wrapper .share-product-text,
        #button_offcanvas_sidebar_left .filters-text,
        .woocommerce-ordering select.orderby,
        .fr-position-text,
        .woocommerce-checkout-review-order .woocommerce-checkout-review-order-table tr td,
        .catalog-ordering .select2-container.orderby a,
        .catalog-ordering .select2-container span,
        .widget_product_categories ul li .count,
        .widget_layered_nav ul li .count,
        .woocommerce-ordering select.orderby,
        .woocommerce .cart-collaterals .cart_totals table.shop_table_responsive tr td::before,
        .woocommerce-page .cart-collaterals .cart_totals table.shop_table_responsive tr td::before,
        .login-register-container .lost-pass-link,
        .woocommerce-cart .cart-collaterals .cart_totals table td .amount,
        .wpb_wrapper .add_to_cart_inline .woocommerce-Price-amount.amount,
        .woocommerce-page .cart-collaterals .cart_totals tr.shipping td,
        .woocommerce-page .cart-collaterals .cart_totals tr.shipping td,
        .woocommerce .cart-collaterals .cart_totals tr.cart-discount th,
        .woocommerce-page .cart-collaterals .cart_totals tr.cart-discount th,
        .woocommerce-thankyou-order-received,
        .woocommerce-order-received .woocommerce table.shop_table tfoot th,
        .woocommerce-order-received .woocommerce-page table.shop_table tfoot th,
        .woocommerce-view-order .woocommerce table.shop_table tfoot th,
        .woocommerce-view-order .woocommerce-page table.shop_table tfoot th,
        .woocommerce-order-received .woocommerce table.shop_table tfoot td,
        .woocommerce-order-received .woocommerce-page table.shop_table tfoot td,
        .woocommerce-view-order .woocommerce table.shop_table tfoot td,
        .woocommerce-view-order .woocommerce-page table.shop_table tfoot td,
        .language-and-currency #top_bar_language_list > ul > li,
        .language-and-currency .wcml_currency_switcher > ul > li.wcml-cs-active-currency,
        .language-and-currency-offcanvas #top_bar_language_list > ul > li,
        .language-and-currency-offcanvas .wcml_currency_switcher > ul > li.wcml-cs-active-currency,
        .woocommerce-order-pay .woocommerce .woocommerce-form-login p.lost_password a,
        .woocommerce-MyAccount-content .woocommerce-orders-table__cell-order-number a,
        .woocommerce form.login .lost_password,
        .comment-reply-title,
        .product_content_wrapper .product_infos .out_of_stock_wrapper .out_of_stock_badge_single,
        .product_content_wrapper .product_infos .woocommerce-variation-availability p.stock.out-of-stock,
        .site-search .widget_product_search .search-field,
        .site-search .widget_search .search-field,
        .site-search .search-form .search-field,
        .site-search .search-text,
        .site-search .search-no-suggestions,
        .latest_posts_grid_wrapper .latest_posts_grid_title,
        p.has-drop-cap:not(:focus):first-letter,
        .paypal-button-tagline .paypal-button-text,
        .tinvwl_add_to_wishlist_button,
        .product-addon-totals,
        body.gbt_custom_notif .page-notifications .gbt-custom-notification-message,
        body.gbt_custom_notif .page-notifications .gbt-custom-notification-message *,
        body.gbt_custom_notif .page-notifications .product_notification_text,
        body.gbt_custom_notif .page-notifications .product_notification_text *,
        body.gbt_classic_notif .woocommerce-error a,
        body.gbt_classic_notif .woocommerce-info a,
        body.gbt_classic_notif .woocommerce-message a,
        body.gbt_classic_notif .woocommerce-notice a,
        .shop_table.cart .product-price .amount,
        .wp-block-media-text .wp-block-media-text__content p,
        p.has-drop-cap:first-letter,
        .wp-block-latest-posts a,
        .wp-block-button,
        .wp-block-cover .wp-block-cover-text,
        .wp-block-subhead,
        .wp-block-image	figcaption,
        .wp-block-quote p,
        .wp-block-quote cite,
        .wp-block-quote .editor-rich-text,
        .wp-block-pullquote p,
        .wp-block-pullquote cite,
        .wp-block-pullquote .editor-rich-text,
        .gbt_18_sk_latest_posts_title,
        .gbt_18_sk_editor_banner_title,
        .gbt_18_sk_editor_slide_title_input,
        .gbt_18_sk_editor_slide_button_input,
        .gbt_18_sk_categories_grid .gbt_18_sk_category_name,
        .gbt_18_sk_categories_grid .gbt_18_sk_category_count,
        .gbt_18_sk_slider_wrapper .gbt_18_sk_slide_button,
        .gbt_18_sk_posts_grid .gbt_18_sk_posts_grid_title,
        .gbt_18_sk_editor_portfolio_item_title,
        .editor-post-title .editor-post-title__input,
        .wc-products-block-preview .product-title,
        .wc-products-block-preview .product-add-to-cart,
        .wc-block-products-category .wc-product-preview__title,
        .wc-block-products-category .wc-product-preview__add-to-cart,
        .wc-block-grid__product-onsale,
        .wc-block-featured-product__price .woocommerce-Price-amount,
        .woocommerce-result-count,
        .widget_price_filter .price_slider_amount,
        .woocommerce ul.products li.product .price,
        .product_content_wrapper .product_infos table.variations  td.label,
        .woocommerce div.product form.cart .reset_variations,
        .cd-quick-view .cd-item-info .product_infos .product_price .price,
        .wc-block-grid__product-price.price,
        .wc-block-order-select__select,
        #powerTip,
        div.wcva_shop_textblock,
        .wcva_filter_textblock,
        .wcva_single_textblock,
        .wp-block-woocommerce-all-reviews .wc-block-review-list-item__product a,
        .cd-quick-view .swatchtitlelabel,
        .cd-quick-view .wcva_attribute_sep,
        .cd-quick-view .wcva_selected_attribute
        {
            font-family: ' . get_option( 'addon_main_typekit_font_face', '' ) . ', sans-serif;
        }
    ';
}

if( !empty( get_option( 'addon_secondary_typekit_font_face', '' ) ) ) {

    $custom_styles .= '
        body,
        p,
        #site-navigation-top-bar,
        .site-title,
        .widget_product_search #searchsubmit,
        .widget_search #searchsubmit,
        .widget_product_search .search-submit,
        .widget_search .search-submit,
        #site-menu,
        .copyright_text,
        blockquote cite,
        table thead th,
        .recently_viewed_in_single h2,
        .woocommerce .cart-collaterals .cart_totals table th,
        .woocommerce-page .cart-collaterals .cart_totals table th,
        .woocommerce .cart-collaterals .shipping_calculator h2,
        .woocommerce-page .cart-collaterals .shipping_calculator h2,
        .woocommerce table.woocommerce-checkout-review-order-table tfoot th,
        .woocommerce-page table.woocommerce-checkout-review-order-table tfoot th,
        .qty,
        .shortcode_banner_simple_inside h4,
        .shortcode_banner_simple_height h4,
        .fr-caption,
        .post_meta_archive,
        .post_meta,
        .yith-wcwl-wishlistaddedbrowse .feedback,
        .yith-wcwl-wishlistexistsbrowse .feedback,
        .product-name span,
        .widget_calendar table tbody a,
        .fr-touch-caption-wrapper,
        .woocommerce .login-register-container p.form-row.remember-me-row label,
        .woocommerce .checkout_login p.form-row label[for="rememberme"],
        .form-row.remember-me-row a,
        .wpb_widgetised_column aside ul li span.count,
        .woocommerce td.product-name dl.variation dt,
        .woocommerce td.product-name dl.variation dd,
        .woocommerce td.product-name dl.variation dt p,
        .woocommerce td.product-name dl.variation dd p,
        .woocommerce-page td.product-name dl.variation dt,
        .woocommerce-page td.product-name dl.variation dd p,
        .woocommerce-page td.product-name dl.variation dt p,
        .woocommerce .select2-container,
        .check_label,
        .woocommerce-page #payment .terms label,
        ul.order_details li strong,
        .widget_recent_comments li,
        .widget_shopping_cart p.total,
        .widget_shopping_cart p.total .amount,
        .mobile-navigation li ul li a,
        .woocommerce #payment div.payment_box p,
        .woocommerce-page #payment div.payment_box p,
        .woocommerce table.cart .cart_item td:before,
        .woocommerce #content table.cart .cart_item td:before,
        .woocommerce-page table.cart .cart_item td:before,
        .woocommerce-page #content table.cart .cart_item td:before,
        .language-and-currency #top_bar_language_list > ul > li > ul > li > a,
        .language-and-currency .wcml_currency_switcher > ul > li.wcml-cs-active-currency > ul.wcml-cs-submenu li a,
        .language-and-currency #top_bar_language_list > ul > li.menu-item-first > ul.sub-menu li.sub-menu-item span.icl_lang_sel_current,
        .language-and-currency-offcanvas  #top_bar_language_list > ul > li > ul > li > a,
        .language-and-currency-offcanvas  .wcml_currency_switcher > ul > li.wcml-cs-active-currency > ul.wcml-cs-submenu li a,
        .language-and-currency-offcanvas  #top_bar_language_list > ul > li.menu-item-first > ul.sub-menu li.sub-menu-item span.icl_lang_sel_current,
        .woocommerce-order-pay .woocommerce .woocommerce-info,
        .select2-results__option,
        body.gbt_classic_notif .woocommerce-error,
        body.gbt_classic_notif .woocommerce-info,
        body.gbt_classic_notif .woocommerce-message,
        body.gbt_classic_notif .woocommerce-notice,
        .gbt_18_sk_editor_banner_subtitle,
        .gbt_18_sk_editor_slide_description_input,
        .woocommerce td.product-name .wc-item-meta li,
        .woocommerce ul.products li.product .woocommerce-loop-product__title,
        .product_content_wrapper .product_infos span.belowtext,
        .wc-block-grid__product-title
        {
            font-family: ' . get_option( 'addon_secondary_typekit_font_face', '' ) . ', serif;
        }
    ';
}

?>
